### ISSUE TITLE
Should we hold extensions' backward-compatible code in this repo or in each extension's repo

### ISSUE THREAD

**Issue by yangyansong-adbe** [adobe/aepsdk-compatibility-ios#10]
Options:
1. Adding all extensions' backward-compatible code in the [aepsdk-compatibility-ios](https://github.com/adobe/aepsdk-compatibility-ios) repo
2. Adding compatibility code in each extension's repo, e.g [aepsdk-userprofile-ios/ACPUserProfile](https://github.com/adobe/aepsdk-userprofile-ios/tree/objc/ACPUserProfile)

**Comment by yangyansong-adbe** [comment]
I'd vote for option 1 because it will be easier to maintain extensions' compatibility code: 

- Each extension can work at its own pace and reducing conflicts (e.g git merge conflicts).
- To release AEP/ACP-AEP extensions using one/the same CI script.

@nporter-adbe @sbenedicadb @shalehaha any comments?

**Comment by nporter-adbe** [comment]
I also vote number 1:

1. I think we should locate all our backward compatible code within the same repo.
2. When providing podspecs such as ACPAnalytics, it would be confusing to have that podspec in the Swift repo

**Comment by sbenedicadb** [comment]
+1 for option 1

**Comment by yangyansong-adbe** [comment]
@sbenedicadb  @nporter-adbe  I agree that option 1 will make the AEPExtension repo clean and simple, but it also means adding more complexity in [aepsdk-compatibility-ios](https://github.com/adobe/aepsdk-compatibility-ios) repo whether we add ACPExtensions' compatibility code to the same/main branch or add it to a different/extension branch.

**Comment by yangyansong-adbe** [comment]
I just chatted with @shalehaha  he also thinks there isn't enough reason to choose #2. So I will add ACPUserProfile compatibility code to [aepsdk-compatibility-ios](https://github.com/adobe/aepsdk-compatibility-ios) repo since most of us want to do #1.
